### ISSUE TITLE
local deploy compiles but 'ic' deploy does not and throws this:

### ISSUE THREAD

**Issue by der0pa** [ORIGYN-SA/minting-starter#20]
Awesome work on this folks :)

terminal out:
Please enter a passphrase for your identity: [hidden]
Decryption complete.
error: parser error
  ┌─ Candid argument:1:28
  │
1 │ (record {owner = principal ""; storage_space = null})
  │                            ^^ Text is too short.

Error: Failed to create argument blob.
Caused by: Failed to create argument blob.
  Invalid argument: Invalid Candid values: Candid parser error: Text is too short. at 27..29
(base) douglassmith@Douglass-MacBook-Pro minting-starter %

**Comment by skilesare** [comment]
I think we just need to do this:  https://forum.dfinity.org/t/origyn-minting-start/15917/3?u=skilesare

Admin_principal is not set for the ic branch and thus the principal parsing fails.

**Comment by Motokoder** [comment]
@der0pa @skilesare The main branch has been updated with this fix.

The documentation for mainnet deployment has also been updated with an important change: https://github.com/ORIGYN-SA/minting-starter/pull/24/files#diff-5a9e6f18bed8859f7751bcc47c4b75e6ec9e757bbec933e08ddb33c8159a6288.

The command to create a new canister should now be executed from the root directory, not the origyn_nft folder, since the deploy.sh script will reference the NFT canister name from the root directory. If you have already created a canister, you can just copy the canister_ids.json file from the ./origyn_nft directory to the root and then run the deploy script.

Both mainnet and local deployments were re-tested and documented here:
Mainnet: https://github.com/ORIGYN-SA/minting-starter/blob/main/docs/terminal-deploy-script-mainnet.md
Local: https://github.com/ORIGYN-SA/minting-starter/blob/main/docs/terminal-deploy-script-localhost.md
